import 'dart:ui';

const Map<String, Offset> elementPositions = {
  "h":  const Offset(0, 0),
  "he": const Offset(17, 0),

  "li": const Offset(0, 1),
  "be": const Offset(1, 1),
  "b":  const Offset(12, 1),
  "c":  const Offset(13, 1),
  "n":  const Offset(14, 1),
  "o":  const Offset(15, 1),
  "f":  const Offset(16, 1),
  "ne": const Offset(17, 1),

  "na": const Offset(0, 2),
  "mg": const Offset(1, 2),
  "al": const Offset(12, 2),
  "si": const Offset(13, 2),
  "p":  const Offset(14, 2),
  "s":  const Offset(15, 2),
  "cl": const Offset(16, 2),
  "ar": const Offset(17, 2),

  "k":  const Offset(0, 3),
  "ca": const Offset(1, 3),
  "sc": const Offset(2, 3),
  "ti": const Offset(3, 3),
  "v":  const Offset(4, 3),
  "cr": const Offset(5, 3),
  "mn": const Offset(6, 3),
  "fe": const Offset(7, 3),
  "co": const Offset(8, 3),
  "ni": const Offset(9, 3),
  "cu": const Offset(10, 3),
  "zn": const Offset(11, 3),
  "ga": const Offset(12, 3),
  "ge": const Offset(13, 3),
  "as": const Offset(14, 3),
  "se": const Offset(15, 3),
  "br": const Offset(16, 3),
  "kr": const Offset(17, 3),

  "rb": const Offset(0, 4),
  "sr": const Offset(1, 4),
  "y":  const Offset(2, 4),
  "zr": const Offset(3, 4),
  "nb": const Offset(4, 4),
  "mo": const Offset(5, 4),
  "tc": const Offset(6, 4),
  "ru": const Offset(7, 4),
  "rh": const Offset(8, 4),
  "pd": const Offset(9, 4),
  "ag": const Offset(10, 4),
  "cd": const Offset(11, 4),
  "in": const Offset(12, 4),
  "sn": const Offset(13, 4),
  "sb": const Offset(14, 4),
  "te": const Offset(15, 4),
  "i":  const Offset(16, 4),
  "xe": const Offset(17, 4),

  "cs": const Offset(0, 5),
  "ba": const Offset(1, 5),
  // lanthanoids
  "hf": const Offset(3, 5),
  "ta": const Offset(4, 5),
  "w":  const Offset(5, 5),
  "re": const Offset(6, 5),
  "os": const Offset(7, 5),
  "ir": const Offset(8, 5),
  "pt": const Offset(9, 5),
  "au": const Offset(10, 5),
  "hg": const Offset(11, 5),
  "tl": const Offset(12, 5),
  "pb": const Offset(13, 5),
  "bi": const Offset(14, 5),
  "po": const Offset(15, 5),
  "at": const Offset(16, 5),
  "rn": const Offset(17, 5),

  "fr": const Offset(0, 6),
  "ra": const Offset(1, 6),
  // Actinoids
  "rf": const Offset(3, 6),
  "db": const Offset(4, 6),
  "sg": const Offset(5, 6),
  "bh": const Offset(6, 6),
  "hs": const Offset(7, 6),
  "mt": const Offset(8, 6),
  "ds": const Offset(9, 6),
  "rg": const Offset(10, 6),
  "cn": const Offset(11, 6),
  "nh": const Offset(12, 6),
  "fl": const Offset(13, 6),
  "mc": const Offset(14, 6),
  "lv": const Offset(15, 6),
  "ts": const Offset(16, 6),
  "og": const Offset(17, 6),

  "la": const Offset(2, 7),
  "ce": const Offset(3, 7),
  "pr": const Offset(4, 7),
  "nd": const Offset(5, 7),
  "pm": const Offset(6, 7),
  "sm": const Offset(7, 7),
  "eu": const Offset(8, 7),
  "gd": const Offset(9, 7),
  "tb": const Offset(10, 7),
  "dy": const Offset(11, 7),
  "ho": const Offset(12, 7),
  "er": const Offset(13, 7),
  "tm": const Offset(14, 7),
  "yb": const Offset(15, 7),
  "lu": const Offset(16, 7),

  "ac": const Offset(2, 8),
  "th": const Offset(3, 8),
  "pa": const Offset(4, 8),
  "u":  const Offset(5, 8),
  "np": const Offset(6, 8),
  "pu": const Offset(7, 8),
  "am": const Offset(8, 8),
  "cm": const Offset(9, 8),
  "bk": const Offset(10, 8),
  "cf": const Offset(11, 8),
  "es": const Offset(12, 8),
  "fm": const Offset(13, 8),
  "md": const Offset(14, 8),
  "no": const Offset(15, 8),
  "lr": const Offset(16, 8),
};